---
name: Bug Report
description: Report a bug or issue with emiprog.
title: "[Bug]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: Describe the bug in 1-2 short sentences
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Code for reproduction
      description: >-
        If possible, please provide the code to reproduce your bug.
      placeholder: Paste your code here. This field is automatically formatted as Python code.
      render: Python
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional information
      description: |
        - What are the conditions under which this bug happens? input parameters, edge cases, etc?
        - Has this worked in earlier versions?
        - Do you know why this bug is happening?
        - Any data required to run your script ?
        - Are you using the latest version of emiproc ?
