
import datetime
import os

from epro.hourly_emissions import speciation as spec

path_emi = os.path.join('oae-art-example', '{online}', 'emis_2015_d1.nc')

output_path = os.path.join('oae-art-example', '{online}', 'hourly')
output_name = "d1_"
prof_path = os.path.join('profiles')

start_date = datetime.date(2015, 6, 26)
end_date = datetime.date(2015, 6, 27)  # included


var_list = ['%se'%s for s in ["NO2","NO","CO","SO2","NH3","ALD",'HCHO','ORA2',
                              'HC3','HC5','HC8','ETH','OL2','OLT','OLI','TOL',
                              'XYL','KET','CSL','VSO4I','VSO4J','VORGPAI',
                              'VORGPAJ','VP25AI','VP25AJ','VANTHA','VSOOT']]



contribution_list = spec.create_mapping()


catlist = (
    [
        ["NOX_A_AREA", "NOX_A_POINT", "NOX_A_ch",
         "NOX_B_AREA", "NOX_B_POINT", "NOX_B_ch",
         "NOX_C_AREA",                "NOX_C_ch",
         "NOX_D_AREA", "NOX_D_POINT", "NOX_D_ch",
         "NOX_E_AREA",                "NOX_E_ch",
         "NOX_F_AREA",                "NOX_F_ch", 
         "NOX_G_AREA",                "NOX_G_ch",
         "NOX_H_AREA", "NOX_H_POINT", "NOX_H_ch",
         "NOX_I_AREA",                "NOX_I_ch", 
         "NOX_J_AREA", "NOX_J_POINT", "NOX_J_ch",
         "NOX_K_AREA",                "NOX_K_ch",
         "NOX_L_AREA",                "NOX_L_ch"],   # for NO2e
        ["NOX_A_AREA", "NOX_A_POINT", "NOX_A_ch",
         "NOX_B_AREA", "NOX_B_POINT", "NOX_B_ch",
         "NOX_C_AREA",                "NOX_C_ch",
         "NOX_D_AREA", "NOX_D_POINT", "NOX_D_ch",
         "NOX_E_AREA",                "NOX_E_ch",
         "NOX_F_AREA",                "NOX_F_ch", 
         "NOX_G_AREA",                "NOX_G_ch",
         "NOX_H_AREA", "NOX_H_POINT", "NOX_H_ch",
         "NOX_I_AREA",                "NOX_I_ch", 
         "NOX_J_AREA", "NOX_J_POINT", "NOX_J_ch",
         "NOX_K_AREA",                "NOX_K_ch",
         "NOX_L_AREA",                "NOX_L_ch"],   # for NOe 
        ["CO_A_AREA", "CO_A_POINT", "CO_A_ch",
         "CO_B_AREA", "CO_B_POINT", "CO_B_ch",
         "CO_C_AREA",               "CO_C_ch",
         "CO_D_AREA", "CO_D_POINT", "CO_D_ch",
         "CO_E_AREA",               "CO_E_ch",
         "CO_F_AREA",               "CO_F_ch",
         "CO_G_AREA",               "CO_G_ch",
         "CO_H_AREA", "CO_H_POINT", "CO_H_ch",
         "CO_I_AREA",               "CO_I_ch",
         "CO_J_AREA", "CO_J_POINT", "CO_J_ch",
         "CO_K_AREA",               "CO_K_ch",
         "CO_L_AREA",               "CO_L_ch"],   # for COe 
       ["SO2_A_AREA", "SO2_A_POINT", "SO2_A_ch",
         "SO2_B_AREA", "SO2_B_POINT", "SO2_B_ch",
         "SO2_C_AREA",               "SO2_C_ch",
         "SO2_D_AREA", "SO2_D_POINT", "SO2_D_ch",
         "SO2_E_AREA",               "SO2_E_ch",
         "SO2_F_AREA",               "SO2_F_ch",
         "SO2_G_AREA",               "SO2_G_ch",
         "SO2_H_AREA", "SO2_H_POINT", "SO2_H_ch",
         "SO2_I_AREA",               "SO2_I_ch",
         "SO2_J_AREA", "SO2_J_POINT", "SO2_J_ch",
         "SO2_K_AREA",               "SO2_K_ch",
         "SO2_L_AREA",               "SO2_L_ch"],   # for SO2e 
       ["NH3_A_AREA", "NH3_A_POINT", "NH3_A_ch",
         "NH3_B_AREA", "NH3_B_POINT", "NH3_B_ch",
         "NH3_C_AREA",               "NH3_C_ch",
         "NH3_D_AREA", "NH3_D_POINT", "NH3_D_ch",
         "NH3_E_AREA",               "NH3_E_ch",
         "NH3_F_AREA",               "NH3_F_ch",
         "NH3_G_AREA",               "NH3_G_ch",
         "NH3_H_AREA", "NH3_H_POINT", "NH3_H_ch",
         "NH3_I_AREA",               "NH3_I_ch",
         "NH3_J_AREA", "NH3_J_POINT", "NH3_J_ch",
         "NH3_K_AREA",               "NH3_K_ch",
         "NH3_L_AREA",               "NH3_L_ch"],   # for NH3e  
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
         "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for ALDe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for HCHOe
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for ORA2e 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for HC3e 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for HC5e 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for HC8e 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for ETHe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for OL2e 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for OLTe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for OLIe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for TOLe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for XYLe
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for KETe 
       ["NMVOC_A_AREA", "NMVOC_A_POINT", "NMVOC_A_ch",
         "NMVOC_B_AREA", "NMVOC_B_POINT", "NMVOC_B_ch",
         "NMVOC_C_AREA",                  "NMVOC_C_ch",
         "NMVOC_D_AREA", "NMVOC_D_POINT", "NMVOC_D_ch",
         "NMVOC_E_AREA",                  "NMVOC_E_ch",
         "NMVOC_F1","NMVOC_F2","NMVOC_F3","NMVOC_F4",
        "NMVOC_F1_ch","NMVOC_F2_ch","NMVOC_F3_ch","NMVOC_F4_ch",
         "NMVOC_G_AREA",                  "NMVOC_G_ch",
         "NMVOC_H_AREA", "NMVOC_H_POINT", "NMVOC_H_ch",
         "NMVOC_I_AREA",                  "NMVOC_I_ch",
         "NMVOC_J_AREA", "NMVOC_J_POINT", "NMVOC_J_ch",
         "NMVOC_L_AREA",                  "NMVOC_L_ch"],  # for CSLe 
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VSO4Ie 
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VSO4Je  
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VORGPAIe  
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VORGPAJe  
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VP25AIe  
       ["PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
         "PM25_C_AREA",                 "PM25_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM25_E_AREA",                 "PM25_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch","PM25_F4_ch",
         "PM25_G_AREA",                 "PM25_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM25_I_AREA",                 "PM25_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM25_K_AREA",                 "PM25_K_ch",
         "PM25_L_AREA",                 "PM25_L_ch"],  # for VP25AJe  
       ["PM10_A_AREA", "PM10_A_POINT", "PM10_A_ch",
        "PM25_A_AREA", "PM25_A_POINT", "PM25_A_ch",
        "PM10_B_AREA", "PM10_B_POINT", "PM10_B_ch",
        "PM25_B_AREA", "PM25_B_POINT", "PM25_B_ch",
        "PM10_C_AREA",               "PM10_C_ch",
        "PM25_C_AREA",                 "PM25_C_ch",
         "PM10_D_AREA", "PM10_D_POINT", "PM10_D_ch",
        "PM25_D_AREA", "PM25_D_POINT", "PM25_D_ch",
         "PM10_E_AREA",               "PM10_E_ch",
        "PM25_E_AREA",                 "PM25_E_ch",
         "PM10_F_AREA",               "PM10_F_ch",
        "PM25_F1","PM25_F2","PM25_F3","PM25_F4",
        "PM25_F1_ch","PM25_F2_ch","PM25_F3_ch",
        "PM25_F4_ch",
        "PM10_G_AREA",               "PM10_G_ch",
        "PM25_G_AREA",               "PM25_G_ch",
         "PM10_H_AREA", "PM10_H_POINT", "PM10_H_ch",
        "PM25_H_AREA", "PM25_H_POINT", "PM25_H_ch",
         "PM10_I_AREA",               "PM10_I_ch",
        "PM25_I_AREA",                 "PM25_I_ch",
         "PM10_J_AREA", "PM10_J_POINT", "PM10_J_ch",
        "PM25_J_AREA", "PM25_J_POINT", "PM25_J_ch",
         "PM10_K_AREA",               "PM10_K_ch",
        "PM25_K_AREA",                 "PM25_K_ch",
         "PM10_L_AREA",               "PM10_L_ch",
        "PM25_L_AREA",                 "PM25_L_ch"],   # for ANTHAe 
       ["PM25_A_AREA", "PM25_A_POINT", "BC_A_ch",
         "PM25_B_AREA", "PM25_B_POINT", "BC_B_ch",
         "PM25_C_AREA",                 "BC_C_ch",
         "PM25_D_AREA", "PM25_D_POINT", "BC_D_ch",
         "PM25_E_AREA",                 "BC_E_ch",
         "PM25_F1","PM25_F2","PM25_F3","PM25_F4","BC_F_ch",
         "PM25_G_AREA",                 "BC_G_ch",
         "PM25_H_AREA", "PM25_H_POINT", "BC_H_ch",
         "PM25_I_AREA",                 "BC_I_ch",
         "PM25_J_AREA", "PM25_J_POINT", "BC_J_ch",
         "PM25_K_AREA",                 "BC_K_ch",
         "PM25_L_AREA",                 "BC_L_ch"]   # for SOOTe  
    ])

tplist = (
    [
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for NO2e    
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for NOe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for COe 
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for SO2e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for NH3e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for ALDe 
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for HCHOe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for ORA2e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for HC3e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for HC5e
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for HC8e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for ETHe
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for OL2e  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for OLTe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for OLIe
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for TOLe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for XYLe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for KETe
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         
         'GNFR_L',           'GNFR_L'],          # for CSLe  
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VSO4Ie   
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VSO4Je
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VORGPAIe   
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VORGPAJe   
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VP25AIe   
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L'],          # for VP25AJe   
        ['GNFR_A', 'GNFR_A', 'GNFR_A','GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B','GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C','GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D','GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E','GNFR_E',           'GNFR_E',
         'GNFR_F',           'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G','GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H','GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I','GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J','GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K','GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L','GNFR_L',           'GNFR_L'],          # for ANTHAe 
        ['GNFR_A', 'GNFR_A', 'GNFR_A',
         'GNFR_B', 'GNFR_B', 'GNFR_B',
         'GNFR_C',           'GNFR_C',
         'GNFR_D', 'GNFR_D', 'GNFR_D',
         'GNFR_E',           'GNFR_E',
         'GNFR_F','GNFR_F','GNFR_F','GNFR_F','GNFR_F',
         'GNFR_G',           'GNFR_G',
         'GNFR_H', 'GNFR_H', 'GNFR_H',
         'GNFR_I',           'GNFR_I',
         'GNFR_J', 'GNFR_J', 'GNFR_J',
         'GNFR_K',           'GNFR_K',
         'GNFR_L',           'GNFR_L']          # for SOOTe  
    ])

 

"""The vertical profile is only applied to point sources.
All area sources have emissions at the floor level.
As such, their profiles are of the shape [1,0,0,...], like GNFR_L"""

vplist = (
    [            
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for NO2e
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for NOe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for COe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for SO2e
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for NH3e               
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for ALDe 
         ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for HCHOe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for ORA2e
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for HC3e  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for HC5e  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for HC8e  
         ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for ETHe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for OL2e  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for OLTe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for OLIe  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for TOLe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for XYLe  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for KETe  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         
         'GNFR_L',           'GNFR_L'],                   # for CSLe  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VSO4Ie  
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VSO4Je   
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VORGPAIe
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VORGPAJe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VP25AIe
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L'],                   # for VP25AJe    
        ['GNFR_L', 'GNFR_A', 'GNFR_L', 'GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L', 'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L', 'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L','GNFR_L','GNFR_L','GNFR_L',   'GNFR_L','GNFR_L','GNFR_L','GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L', 'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L', 'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L', 'GNFR_L',           'GNFR_L'],                   # for ANTHAe 
        ['GNFR_L', 'GNFR_A', 'GNFR_L',
         'GNFR_L', 'GNFR_B', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_D', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L','GNFR_L','GNFR_L','GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_H', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L', 'GNFR_J', 'GNFR_L',
         'GNFR_L',           'GNFR_L',
         'GNFR_L',           'GNFR_L']                   # for SOOTe  
    ])









